#https://github.com/ivan-hc/AM/blob/main/programs/x86_64/obs-studio
name: "obs-studio"
bin_name: "obs-studio"
bins:
  - "obs-studio.AppImage"
  - "obs-studio.NixAppImage"
category:
 - "multimedia"
 - "screenrecording"
 - "video"
description: "FOSS cross-platform screencasting and streaming app (AppImage|NixAppImage)"
note: "This PKG has Multiple Formats (CI_VERIFIED: https://github.com/obsproject/obs-studio/actions)"
web_url: "https://obsproject.com"
path: "/"
src_url: "https://github.com/obsproject/obs-studio"