name: "advanced-passgen"
bin_name: "advanced-passgen"
bins:
  - "advanced-passgen.AppImage"
category:
 - "passgen"
 - "password-manager"
description: "Advanced Password Generator (AppImage)"
note: "(CI_VERIFIED: https://github.com/CodeDead/Advanced-PassGen/actions)"
web_url: "https://advancedpassgen.codedead.com"
path: "/"
src_url: "https://github.com/CodeDead/Advanced-PassGen"