name: "android-platform-tools.appimage"
bin_id: "xxx.com.android.developer"
bin_name: "android-platform-tools"
bins:
  - "android-platform-tools.appimage"
category:
 - "ConsoleOnly"
 - "Utility"
description: "Android SDK Platform-Tools (adb, fastboot & more)"
note: "Community Created AppImage. Check/Report @ https://github.com/Samueru-sama/android-tools-AppImage"
web_url: "https://developer.android.com/tools/releases/platform-tools"
path: "/"
src_url: "https://android.googlesource.com/platform/tools/base"