name: "android-tools"
bin_name: "android-tools"
bins:
  - "android-tools.AppImage"
category:
 - "android"
 - "utility"
description: "Android SDK Platform-Tools that interface with the Android platform, primarily adb and fastboot (AppImage)"
note: "This PKG was built from Source using go-appimagetool"
web_url: "https://developer.android.com/tools/releases/platform-tools"
path: "/"
src_url: "https://android.googlesource.com/platform/tools/base"