name: "brave.appimage"
bin_id: "com.brave.Browser"
bin_name: "brave"
bins:
  - "brave.appimage"
category:
 - "WebBrowser"
description: "Privacy-oriented browser for Desktop and Laptop computers"
note: "Community Created AppImage. Check/Report @ https://github.com/srevinsaju/Brave-AppImage"
web_url: "https://brave.com"
path: "/"
src_url: "https://github.com/brave/brave-browser"