name: "chromium.nixappimage"
bin_id: "org.chromium.Chromium"
bin_name: "chromium"
bins:
  - "chromium.nixappimage"
category:
 - "WebBrowser"
description: "Open source web browser from Google"
note: "NixAppImages: https://l.ajam.dev/nix-appimage"
web_url: "https://www.chromium.org"
path: "/"
src_url: "https://chromium.googlesource.com/chromium/src.git"