name: "dunst.appimage"
bin_id: "xxx.org.dunst-project"
bin_name: "dunst"
bins:
  - "dunst.appimage"
category:
 - "System"
 - "Monitor"
description: "Lightweight and customizable notification daemon"
note: "Community Created AppImage. Check/Report @ https://github.com/Samueru-sama/dunst-AppImage"
web_url: "https://dunst-project.org"
path: "/"
src_url: "https://github.com/dunst-project/dunst"