name: "firefox-esr.appimage"
bin_id: "org.mozilla.firefox"
bin_name: "firefox"
bins:
  - "firefox-esr.appimage"
category:
 - "WebBrowser"
description: "A web browser built from Firefox source tree (ESR)"
note: "Community Created AppImage. Check/Report @ https://github.com/srevinsaju/Firefox-Appimage"
web_url: "http://www.mozilla.com"
path: "/"
src_url: "https://hg.mozilla.org/mozilla-central"