name: "gnome-boxes.appimage"
bin_id: "org.gnome.Boxes"
bin_name: "gnome-boxes"
bins:
  - "gnome-boxes.appimage"
category:
 - "Monitor"
description: "Simple GNOME application to access remote or virtual systems"
note: "Community Created AppImage. Check/Report @ https://github.com/ivan-hc/Boxes-appimage"
web_url: "https://apps.gnome.org/Boxes/"
path: "/"
src_url: "https://gitlab.gnome.org/GNOME/gnome-boxes"