name: "i3.appimage"
bin_id: "org.i3wm.i3"
bin_name: "i3"
bins:
  - "i3.appimage"
category:
 - "System"
 - "Utility"
description: "A Tiling Window Manager"
note: "Community Created AppImage based on Conty (ArchLinux). Check/Report @ https://github.com/Samueru-sama/i3-AppImage"
web_url: "https://i3wm.org"
path: "/"
src_url: "https://github.com/i3/i3"