name: "lite-xl.appimage"
bin_id: "com.lite_xl.LiteXL"
bin_name: "lite-xl"
bins:
  - "lite-xl.appimage"
category:
 - "IDE"
 - "TextEditor"
description: "A lightweight, simple, fast, feature-filled, and extremely extensible Text Editor"
note: "Officially Created AppImage. Check/Report @ https://github.com/lite-xl/lite-xl"
web_url: "https://lite-xl.com"
path: "/"
src_url: "https://github.com/lite-xl/lite-xl"