name: "opera.appimage"
bin_id: "com.opera.Opera"
bin_name: "opera"
bins:
  - "opera.appimage"
category:
 - "WebBrowser"
description: "Faster, safer and smarter web browser"
note: "Community Created AppImage. Check/Report @ https://github.com/ivan-hc/Opera-appimage"
web_url: "https://www.opera.com"
path: "/"
src_url: "https://github.com/ivan-hc/Opera-appimage"