name: "persepolis"
bin_name: "persepolis"
bins:
  - "persepolis.NixAppImage"
  - "persepolis.NixAppImage"
category:
 - "downloader"
 - "multimedia"
description: "A Download Manager (GUI for aria2) written in Python (AppImage|NixAppImage)"
note: "(CI_VERIFIED: NONE)"
web_url: "https://persepolisdm.github.io"
path: "/"
src_url: "https://github.com/persepolisdm/persepolis"