name: "simplex-chat-desktop.appimage"
bin_id: "chat.simplex.simplex"
bin_name: "simplex-chat-desktop"
bins:
  - "simplex-chat-desktop.appimage"
category:
 - "Chat"
 - "IRCClient"
 - "Security"
description: "Messaging network operating without user identifiers of any kind"
note: "Officially Created AppImage. Check/Report @ https://github.com/simplex-chat/simplex-chat"
web_url: "https://simplex.chat"
path: "/"
src_url: "https://github.com/simplex-chat/simplex-chat"