name: "steam.appimage"
bin_id: "com.valvesoftware.Steam"
bin_name: "steam"
bins:
  - "steam.appimage"
category:
 - "Game"
description: "A video game digital distribution service and storefront from Valve"
note: "Community Created AppImage based on Conty (ArchLinux). Check/Report @ https://github.com/ivan-hc/Steam-appimage"
web_url: "https://store.steampowered.com/about/"
path: "/"
src_url: "https://github.com/ivan-hc/Steam-appimage"