#https://github.com/lycheeverse/lychee-action
name: 🔎 Check Links 🔗

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "15 0 * * 1" #12:15 AM UTC --> 06:00 AM NPT Tue

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v4
        with:
          path: main
          filter: "blob:none"
          
      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v2
        with:
          fail: false

      - name: Create Issue From File
        if: steps.lychee.outputs.exit_code != 0
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
